import ExcelJS from "exceljs";
import { saveAs } from "file-saver";

const KMC_BLUE = "FF003893";
const KMC_RED = "FFC8102E";
const KMC_MANTRA = "A Cut Above The Rest";

const arrayBufferToBase64 = (buffer) => {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunkSize));
  }
  return window.btoa(binary);
};

const fetchImageAsBase64 = async (imageUrl) => {
  if (!imageUrl) return null;
  try {
    // If it's a relative path starting with /src, we might need to handle it differently in production
    // But for Vite dev/build, passing the imported asset URL should work.
    const response = await fetch(imageUrl);
    if (!response.ok) return null;
    const blob = await response.blob();
    const base64 = arrayBufferToBase64(await blob.arrayBuffer());
    const extension = blob.type?.split("/")?.[1] || "png";
    return { base64, extension };
  } catch (error) {
    console.error("Failed to fetch image for Excel:", error);
    return null;
  }
};

const applyHeaderStyling = (row) => {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: KMC_BLUE } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin", color: { argb: "FF000000" } },
      left: { style: "thin", color: { argb: "FF000000" } },
      bottom: { style: "thin", color: { argb: "FF000000" } },
      right: { style: "thin", color: { argb: "FF000000" } }
    };
  });
  row.height = 25;
};

const addTableWorksheet = (workbook, sheetName, data, headers = null) => {
  if (!data || !data.length) return null;
  const firstRow = data[0];
  const keys = headers?.length ? headers : Object.keys(firstRow);
  const worksheet = workbook.addWorksheet(sheetName);

  worksheet.columns = keys.map((key) => {
    const width = Math.max(
      15,
      key.length + 5,
      ...data.map((row) => String(row[key] ?? "").length + 2)
    );
    return { header: key, key, width: Math.min(width, 50) };
  });

  worksheet.addRows(data.map((row) => keys.map((key) => row[key] ?? "")));
  applyHeaderStyling(worksheet.getRow(1));
  worksheet.views = [{ state: "frozen", ySplit: 1 }];

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber > 1) {
      row.eachCell((cell) => {
        cell.border = {
          bottom: { style: "thin", color: { argb: "FFEEEEEE" } },
          right: { style: "thin", color: { argb: "FFEEEEEE" } }
        };
        if (typeof cell.value === "number") {
          cell.numFmt = "#,##0.00";
          cell.alignment = { horizontal: "right" };
        }
      });
      row.height = 20;
    }
  });

  return worksheet;
};

const addSummaryWorksheet = async (workbook, title, summaryData, logoUrl, sloganUrl) => {
  const worksheet = workbook.addWorksheet("Executive Summary");
  worksheet.properties.defaultRowHeight = 22;

  // Add Logo if available
  const logo = logoUrl ? await fetchImageAsBase64(logoUrl) : null;
  if (logo) {
    const imageId = workbook.addImage({ base64: logo.base64, extension: logo.extension });
    worksheet.addImage(imageId, {
      tl: { col: 0, row: 0 },
      ext: { width: 100, height: 100 },
    });
  }

  // Add Slogan/Mantra image if available
  const slogan = sloganUrl ? await fetchImageAsBase64(sloganUrl) : null;
  if (slogan) {
    const sloganId = workbook.addImage({ base64: slogan.base64, extension: slogan.extension });
    worksheet.addImage(sloganId, {
      tl: { col: 3, row: 0 },
      ext: { width: 250, height: 60 },
    });
  }

  // Header Title
  worksheet.mergeCells("A6", "F7");
  const titleCell = worksheet.getCell("A6");
  titleCell.value = title || "KMC Dashboard Report";
  titleCell.font = { size: 22, bold: true, color: { argb: KMC_BLUE } };
  titleCell.alignment = { vertical: "middle", horizontal: "center" };

  // Mantra Text
  worksheet.mergeCells("A8", "F8");
  const mantraCell = worksheet.getCell("A8");
  mantraCell.value = KMC_MANTRA;
  mantraCell.font = { size: 14, italic: true, color: { argb: KMC_RED }, bold: true };
  mantraCell.alignment = { vertical: "middle", horizontal: "center" };

  worksheet.addRow([]);
  worksheet.addRow(["REPORT METADATA"]);
  const metaHeader = worksheet.getRow(worksheet.lastRow.number);
  metaHeader.font = { bold: true, color: { argb: "FFFFFFFF" } };
  metaHeader.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF444444" } };

  worksheet.addRow(["Report Name", title || "General Export"]);
  worksheet.addRow(["Generated By", "KMC Livestock Tracking System"]);
  worksheet.addRow(["Date Generated", new Date().toLocaleString("en-GB")]);
  worksheet.addRow(["Status", "Official Record"]);

  worksheet.addRow([]);
  worksheet.addRow(["KEY DATA SUMMARY"]);
  const summaryHeader = worksheet.getRow(worksheet.lastRow.number);
  summaryHeader.font = { bold: true, color: { argb: "FFFFFFFF" } };
  summaryHeader.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: KMC_BLUE } };

  if (summaryData && Object.keys(summaryData).length) {
    Object.entries(summaryData).forEach(([label, value]) => {
      const row = worksheet.addRow([label, value]);
      row.getCell(1).font = { bold: true, color: { argb: "FF333333" } };
      row.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF5F5F5" } };
      row.getCell(2).alignment = { vertical: "middle", horizontal: "left", wrapText: true };
      row.getCell(2).font = { bold: true, color: { argb: KMC_BLUE } };
    });
  } else {
    worksheet.addRow(["No summary data provided"]);
  }

  worksheet.columns = [
    { width: 25 },
    { width: 40 },
    { width: 15 },
    { width: 15 },
    { width: 15 },
    { width: 15 },
  ];

  // Apply some border to the summary table
  const lastRow = worksheet.lastRow.number;
  for (let i = 11; i <= lastRow; i++) {
    const row = worksheet.getRow(i);
    row.getCell(1).border = { bottom: { style: "thin" }, right: { style: "thin" } };
    row.getCell(2).border = { bottom: { style: "thin" }, right: { style: "thin" } };
  }

  return worksheet;
};

const addAnalysisSheet = async (workbook, analysis) => {
  if (!analysis || !analysis.data || !analysis.data.length) return null;
  const sheetName = analysis.sheetName || "Data Analysis";
  const worksheet = workbook.addWorksheet(sheetName);

  // Title
  worksheet.mergeCells("A1", "H2");
  const titleCell = worksheet.getCell("A1");
  titleCell.value = analysis.title || "Dataset Analysis";
  titleCell.font = { size: 18, bold: true, color: { argb: KMC_BLUE } };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };

  let currentRow = 4;

  if (analysis.description) {
    worksheet.mergeCells(`A${currentRow}`, `H${currentRow}`);
    worksheet.getCell(`A${currentRow}`).value = analysis.description;
    worksheet.getCell(`A${currentRow}`).font = { italic: true };
    currentRow += 2;
  }

  const headers = analysis.headers || Object.keys(analysis.data[0]);
  const headerRow = worksheet.getRow(currentRow);
  headers.forEach((h, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: KMC_BLUE } };
    cell.alignment = { horizontal: "center" };
    cell.border = { outline: true, style: "thin" };
  });
  currentRow++;

  analysis.data.forEach((rowData) => {
    const row = worksheet.getRow(currentRow);
    headers.forEach((h, i) => {
      const cell = row.getCell(i + 1);
      cell.value = rowData[h];
      cell.border = { bottom: { style: "hair" }, right: { style: "hair" } };
      if (typeof cell.value === "number") {
        cell.numFmt = "#,##0.00";
      }
    });
    currentRow++;
  });

  worksheet.columns = headers.map(() => ({ width: 20 }));

  return worksheet;
};

export const exportToExcel = async (data, fileName = "export", headers = null, options = {}) => {
  if (!data || !Array.isArray(data) || data.length === 0) {
    alert("No data available to export");
    return;
  }

  const workbook = new ExcelJS.Workbook();
  workbook.creator = "KMC Livestock Tracking System";
  workbook.lastModifiedBy = "KMC Admin";
  workbook.created = new Date();
  workbook.modified = new Date();

  const summaryData = options.summaryData || {};
  const logoUrl = options.logoUrl;
  const sloganUrl = options.sloganUrl;
  const analysisSheets = options.analysisSheets || [];

  // 1. Executive Summary Sheet
  await addSummaryWorksheet(workbook, options.title || "KMC Dashboard Export", summaryData, logoUrl, sloganUrl);

  // 2. Raw Data Sheet
  addTableWorksheet(workbook, options.sheetName || "Detailed Data", data, headers);

  // 3. Additional Analysis Sheets
  for (const analysis of analysisSheets) {
    await addAnalysisSheet(workbook, analysis);
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 16);
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  saveAs(blob, `${fileName}_${timestamp}.xlsx`);
};

